# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.cache/wt [current_project]
set_property parent.project_path C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/s_box_invert.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/mult_e.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/mult_d.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/mult_b.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/mult_9.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/s_boxing.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/shift_rows.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/inv_mix_columns.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/InvSub.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/key_expansion.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/InvCipher.vhd
  C:/Users/Darius/Desktop/Y4S1/EE4218/AES_package/AES_package.srcs/sources_1/new/AES_v1_0.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top AES_InvCipher_v1_0 -part xc7z020clg484-1


write_checkpoint -force -noxdef AES_InvCipher_v1_0.dcp

catch { report_utilization -file AES_InvCipher_v1_0_utilization_synth.rpt -pb AES_InvCipher_v1_0_utilization_synth.pb }
